apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/stable/manifests/install.yaml
- external-secrets.yaml

- target:
    kind: ConfigMap
    name: argocd-image-updater-config
  patch: |-
    - op: add
      path: /data/registries.conf
      value: |
        registries:
        - name: Docker Hub
          api_url: https://registry-1.docker.io
          prefix: docker.io
          credentials: pullsecret:argocd/dockerhub-secret
          defaultns: library
