apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Could also be curled and saved first to provision the installation in a restricted environment
  # Use HA installation for production
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.2.0/manifests/install.yaml

patches:
  - target:
      kind: Service
      name: argocd-server
    path: argocd-server-service.yaml
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
    path: argocd-cmd-params-cm.yaml
  - target:
      kind: ConfigMap
      name: argocd-cm
    path: argo-cm.yaml
  - target:
      kind: NetworkPolicy
      name: argocd-repo-server-network-policy
    path: argocd-repo-server-netpol-patch.yaml
