apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
helmCharts:
  - name: istiod
    releaseName: istiod
    version: 1.28.0
    repo: https://istio-release.storage.googleapis.com/charts
    valuesInline:
      meshConfig:
        defaultConfig:
          discoveryAddress: istiod.istio-system.svc:15012
          proxyMetadata:
            ISTIO_META_ENABLE_HBONE: "true"
      pilot:
        env:
          PILOT_ENABLE_AMBIENT: "true"
          CA_TRUSTED_NODE_ACCOUNTS: "default/ztunnel,kube-system/ztunnel,istio-system/ztunnel,istio-ingress/ztunnel"
      global:
        variant: distroless
        istioNamespace: istio-system
