apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
commonAnnotations:
  argocd.argoproj.io/sync-wave: "3"
helmCharts:
  - name: cni
    releaseName: istio-cni
    version: 1.28.0
    repo: https://istio-release.storage.googleapis.com/charts
    valuesInline:
      ambient:
        enabled: true
      global:
        variant: distroless
