apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storage

resources:
  - demo-app/
  - mlflow/

helmCharts:
  - name: cloudnative-pg
    releaseName: cnpg-cloudnative-pg
    version: 0.24.0
    repo: https://cloudnative-pg.github.io/charts
