apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ai-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: git@github.com:opencloudhub/gitops.git
      revision: HEAD
      directories:
      - path: src/team-apps/ai/*
  template:
    metadata:
      name: "{{index .path.segments 3}}"
      labels:
        app.kubernetes.io/name: "{{index .path.segments 3}}"
        app.kubernetes.io/part-of: ai
        app.kubernetes.io/managed-by: argocd
      annotations:
        argocd.argoproj.io/sync-wave: |
          {{- if eq (index .path.segments 3) "mlflow" }}200
          {{- else if eq (index .path.segments 3) "argo-workflows" }}210
          {{- else }}220{{- end }}
        argocd.argoproj.io/sync-options: |
          {{- if eq (index .path.segments 3) "ray" }}
          ServerSideApply=true,RespectIgnoreDifferences=true
          {{- else }}
          RespectIgnoreDifferences=true
          {{- end }}
    spec:
      project: ai
      source:
        repoURL: git@github.com:opencloudhub/gitops.git
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      ignoreDifferences:
      - group: external-secrets.io
        kind: ExternalSecret
        jsonPointers:
        - /status
        - /spec/data
