apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
# components:
# - https://github.com/argoproj-labs/argocd-extensions/manifests
resources:
- base/
- external-secrets.yaml
- http-route.yaml
- service-monitors.yaml
- root-app-meta.yaml
