apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: models
resources:
  - wine-classifier-service.yaml
  # - fashion-mnist-classifier-service.yaml
  # - qwen-vl-radiology-vqa-service.yaml
