githubConfigUrl: "https://github.com/OpenCloudHub"
githubConfigSecret: arc-github-secret
runnerGroup: local-minikube
minRunners: 0
maxRunners: 2
controllerServiceAccount:
  namespace: arc-systems
  name: arc-gha-rs-controller
