apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app
resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
images:
  - name: opencloudhuborg/demo-app-frontend
    newTag: main-7650d74
