apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: git@github.com:opencloudhub/gitops.git
        revision: HEAD
        directories:
          - path: src/platform/*/*
  template:
    metadata:
      name: "{{index .path.segments 3}}"
      labels:
        app.kubernetes.io/name: "{{index .path.segments 3}}"
      annotations:
        argocd.argoproj.io/sync-options: |
          {{- if eq (index .path.segments 3) "cloudnative-pg" }}
          SkipDryRunOnMissingResource=true,ServerSideApply=true
          {{- else }}
          SkipDryRunOnMissingResource=true
          {{- end }}
        argocd.argoproj.io/sync-wave: |-
          {{- $app := index .path.segments 3 -}}
          {{- if or (eq $app "istio") (eq $app "cert-manager") (eq $app "external-secrets") -}}
          -3
          {{- else if or (eq $app "cloudnative-pg") (eq $app "minio-operator") -}}
          -2
          {{- else if or (eq $app "minio-tenant") (eq $app "argocd-image-updater") -}}
          -1
          {{- else if or (eq $app "gateway") (eq $app "mlflow") (eq $app "ray-operator") (eq $app "argo-workflows") -}}
          1
          {{- else -}}
          0
          {{- end }}
    spec:
      project: platform
      source:
        repoURL: git@github.com:opencloudhub/gitops.git
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
        #   - RespectIgnoreDifferences=true
      ignoreDifferences:
        # Istio webhook failurePolicy
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: istio-validator-istio-system
          jsonPointers:
            - /webhooks/0/failurePolicy
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: istiod-default-validator
          jsonPointers:
            - /webhooks/0/failurePolicy
        # Ignore resourceFieldRef divisor field (Istio ztunnel issue)
        - group: apps
          kind: DaemonSet
          jqPathExpressions:
            - ".spec.template.spec.containers[].env[]?.valueFrom.resourceFieldRef.divisor"
        - group: apps
          kind: Deployment
          jqPathExpressions:
            - ".spec.template.spec.containers[].env[]?.valueFrom.resourceFieldRef.divisor"
        # Ignore ExternalSecret operator-added fields
        - group: external-secrets.io
          kind: ExternalSecret
          jqPathExpressions:
            - ".spec.data[].remoteRef.conversionStrategy"
            - ".spec.data[].remoteRef.decodingStrategy"
            - ".spec.data[].remoteRef.metadataPolicy"
        - group: external-secrets.io
          kind: ExternalSecret
          jsonPointers:
            - /status
            - /metadata/generation
            - /metadata/resourceVersion
            - /metadata/managedFields
