apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app
resources:
  - deployment-backend.yaml
  - service-backend.yaml
  - deployment-frontend.yaml
  - service-frontend.yaml
  - http-route.yaml
