apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops

resources:
  - mlops-pipeline.yaml
  - modules/training.yaml
  - modules/mlflow.yaml
  - modules/deployment.yaml
  - modules/testing.yaml
