githubConfigUrl: "https://github.com/OpenCloudHub"
githubConfigSecret:
  name: arc-github-secret
  namespace: arc-systems
minRunners: 0
maxRunners: 2
controllerServiceAccount:
  namespace: arc-systems
  name: arc-gha-rs-controller
