apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
commonAnnotations:
  argocd.argoproj.io/sync-wave: "4"
helmCharts:
  - name: ztunnel
    releaseName: istio-ztunnel
    version: 1.28.0
    repo: https://istio-release.storage.googleapis.com/charts
    valuesInline:
      meshConfig:
        defaultConfig:
          proxyMetadata:
            ISTIO_META_ENABLE_HBONE: "true"
      global:
        variant: distroless
        istioNamespace: istio-system
