apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: git@github.com:opencloudhub/gitops.git
        revision: HEAD
        directories:
          - path: src/team-apps/demo-app/*
  template:
    metadata:
      name: "{{index .path.segments 3}}"
      labels:
        app.kubernetes.io/name: "{{index .path.segments 3}}"
        app.kubernetes.io/part-of: demo-app
        app.kubernetes.io/managed-by: argocd
      annotations:
        # Image Updater configuration
        argocd-image-updater.argoproj.io/image-list: app=opencloudhuborg/{{index .path.segments 3}}
        argocd-image-updater.argoproj.io/app.update-strategy: digest
        argocd-image-updater.argoproj.io/app.allow-tags: regexp:^main-[0-9a-f]{7}$
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
        argocd-image-updater.argoproj.io/git-branch: main
    spec:
      project: demo-app  # or create a 'demo-app' project if you prefer
      source:
        repoURL: git@github.com:opencloudhub/gitops.git
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
