apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-mlops

resources:
- mlops-pipeline.yaml
- modules/compute.yaml
- modules/training.yaml
- modules/mlflow.yaml
- modules/deployment.yaml
