apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai

resources:
- ml-ops-pipeline.yaml
- modules/compute.yaml
- modules/training.yaml
- modules/mlflow.yaml
- modules/approval.yaml
- modules/deployment.yaml
