apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-secret-stores.yaml

helmCharts:
  - name: external-secrets
    releaseName: external-secrets
    version: 1.0.0
    repo: https://charts.external-secrets.io
    includeCRDs: true
    valuesInline:
      namespaceOverride: external-secrets
