apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - cluster-secret-stores.yaml
  - cluster-secrets
  - external-secrets

helmCharts:
  - name: external-secrets
    releaseName: external-secrets
    version: 1.0.0
    repo: https://charts.external-secrets.io
    includeCRDs: true
    valuesInline:
      namespaceOverride: external-secrets
      # certController:
      #   enabled: true
      # webhook:
      #   certManager:
      #     enabled: true
      #     addInjectorAnnotations: true
      #     cert:
      #       create: true
      #       issuerRef:
      #         kind: ClusterIssuer
      #         name: ca-issuer
